function [ X_constant ] = x_constant( ti, tj,a,om, t)
%% Constant segment from ti to tj

X_constant  = a/2*(exp(om*t)*(exp(-om*ti)-exp(-om*tj))).*...
             (1 - stepfun(t,ti))...
          + a/2*(2 - exp(-om*(t-ti)) - exp(-om*(tj-t))).*...
             (stepfun(t,ti)-stepfun(t,tj))...
          + a/2*(exp(-om*t)*(exp(om*tj)-exp(om*ti))).*...
             stepfun(t,tj);


end

