function [ Cubicj ] = x_cubic( ti,tj,Tji,om,t )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
Cubicj1 = om/2*(6/om^4*exp(om*(t-ti)) - ...
        exp(om*(t-tj))*(Tji^3/om + 3*Tji^2/om^2+6*Tji/om^3+6/om^4)).*...
        (1 - stepfun(t,ti));
Cubicj2 = om/2*(2*(t-ti).^3/om + 12*(t-ti)/om^3 -...
         exp(om*(t-tj))*(Tji^3/om + 3*Tji^2/om^2+6*Tji/om^3+6/om^4) + ...
         6*exp(-om*(t-ti))/om^4).*...
         (stepfun(t,ti)-stepfun(t,tj));
Cubicj3 = om/2*(6/om^4*exp(-om*(t-ti)) + ...
        exp(-om*(t-tj))*(Tji^3/om - 3*Tji^2/om^2+6*Tji/om^3-6/om^4)).*...
        stepfun(t,tj);
Cubicj = Cubicj1 + Cubicj2 + Cubicj3;

end

