function [ Quadj  ] = x_quadric( ti,tj,Tji,om,t )
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
Quadj1 = om/2*(2/om^3*exp(om*(t-ti)) - ...
        exp(om*(t-tj))*(Tji^2/om + 2*Tji/om^2+2/om^3)).*...
        (1 - stepfun(t,ti));
Quadj2 = om/2*(2*(t-ti).^2/om + 4/om^3 -...
         exp(om*(t-tj))*(Tji^2/om + 2*Tji/om^2+2/om^3) - ...
         2*exp(-om*(t-ti))/om^3).*...
         (stepfun(t,ti)-stepfun(t,tj));
Quadj3 = om/2*(-2/om^3*exp(-om*(t-ti)) + ...
        exp(-om*(t-tj))*(Tji^2/om - 2*Tji/om^2+2/om^3)).*...
        stepfun(t,tj);
Quadj = Quadj1 + Quadj2 + Quadj3;

end

